title: Satyam Sundaram
description: Personal site & long-term knowledge base
url: https://satyamsundaram.com

markdown: kramdown
# theme: minima

collections:
  projects:
    output: true
    permalink: /projects/:name/